image: debian:jessie

cache:
  key: "FIFu"
  paths:
    - cache

before_script:
  - ./install_requirements.sh

stages:
  - build

build_check:
 stage: build
 script:
   - ./build.sh
 tags:
   - docker
